1. 2 * 3 영행렬, 모든 성분이 1인 2 * 2 행렬, 모든 성분이 3인 3 * 2 행렬, 2 * 2 단위행렬을 만들어 출력하는 프로그램을 작성하여라

In [13]:
import numpy as np

# 2 * 3 영행렬
print(np.zeros(shape=[2,3]))

# 모든 성분 1인  2 * 2 행렬
print(np.ones(shape=[2,2]))

# 모든 성분 3인 3 * 2 인 행렬
print(np.ones(shape=[3,2]) * 3)

# 단위 행렬 2 * 2
M = np.zeros((2,2))
M[0][0]=1
M[1][1]=1
print(M)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]]
[[1. 0.]
 [0. 1.]]


In [12]:
# 책 풀이

# 2 * 3 영행렬
print(np.zeros((2,3)))

# 모든 성분 1인  2 * 2 행렬
print(np.ones((2,2)))

# 모든 성분 3인 3 * 2 인 행렬
print(np.full((3,2),3))

# 단위 행렬 2 * 2
print(np.eye(2))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[3 3]
 [3 3]
 [3 3]]
[[1. 0.]
 [0. 1.]]


2. 가우스 조단 소거법을 수행하는 gauss()라는 함수를 정의하고, 이 함수를 이용하여 다음 연립선형방정식의 해를 구하여라.<br>
gauss(A) 의 입력으로 주어지는 A 는 주어진 연립선형방정식에 대한 첨가행렬이다.

2* x1 + 2* x2+ 4* x3 = 18 <br>
x1 + 3* x3 + 2* x3 = 13 <br>
3* x1 + x2 + 3 * x3 = 14


In [16]:
A = np.array([[2,2,4,18],[1,3,2,13],[3,1,3,14]])

In [18]:
for i in range(A.shape[0]):
    print(A[i][i])

2
3
3
